#!/usr/bin/env bash
# Android emulator test: VPN + "Private DNS" (strict mode).
# Runs inside reactivecircus/android-emulator-runner. Expects:
#   app-debug.apk in the repo root, test SOCKS5 proxy on the host at 10.0.2.2:21080 (up/pp).
set -u
PKG=com.tainavpn.app
OUT=/tmp/android-test
mkdir -p $OUT
fail=0
note() { echo "::notice::$*"; }

adb install -r -g app-debug.apk || { echo "::error::install failed"; exit 1; }

# Private DNS strict mode, like on the user's phone
PDNS_MODE="${PDNS_MODE:-hostname}"
adb shell settings put global private_dns_mode "$PDNS_MODE"
adb shell settings put global private_dns_specifier one.one.one.one
sleep 8
adb shell dumpsys connectivity | grep -iE "PrivateDns|private_dns" | head -5

# client config generated by the real app code (ui/app.js), as on Android
node -e '
  const m = require("./ui/app.js");
  const p = { type: "socks", server: "10.0.2.2", port: 21080, username: "up", password: "pp" };
  m._setStore({ profiles: [p], bypassLan: true, mode: "tun" }, "android");
  const cfg = JSON.parse(m.buildConfig(p));
  cfg.log = { level: "debug", timestamp: true };
  require("fs").writeFileSync("/tmp/client.json", JSON.stringify(cfg, null, 2));
'
adb push /tmp/client.json /data/local/tmp/config.json
adb shell "run-as $PKG sh -c 'mkdir -p files && cat /data/local/tmp/config.json > files/config.json'" \
  || adb shell "run-as $PKG sh -c 'cat > files/config.json'" < /tmp/client.json
adb shell run-as $PKG ls -la files/

# allow the VPN without the consent dialog and start it
adb shell appops set $PKG ACTIVATE_VPN allow
adb shell am start -W -n $PKG/.MainActivity --ez test_connect true
sleep 15

adb shell dumpsys connectivity > $OUT/connectivity.txt
grep -n "VPN" $OUT/connectivity.txt | head -20

# 1) DNS through the VPN works (ping prints the resolved address even without replies)
for host in example.com google.com; do
  r=$(adb shell "ping -c 1 -W 5 $host 2>&1" | head -2)
  echo "$r"
  if echo "$r" | grep -q "PING $host ("; then note "DNS ok: $host"; else echo "::error::DNS failed for $host: $r"; fail=1; fi
done

# 2) the "Private DNS server cannot be accessed" notification
sleep 10
adb shell dumpsys notification --noredact > $OUT/notifications.txt 2>&1
if grep -qiE "private.?dns|PRIVATE_DNS" $OUT/notifications.txt; then
  grep -iE -B3 -A6 "private.?dns|PRIVATE_DNS" $OUT/notifications.txt | head -60
  echo "::error::Android shows the Private DNS notification"
  fail=1
else
  note "no Private DNS notification"
fi

# 3) private DNS validation state of the networks
adb shell dumpsys connectivity | grep -iE "ValidatedPrivateDns|PrivateDnsServerName|PRIVATE_DNS_BROKEN|privateDnsBroken" | head -20 | tee $OUT/pdns.txt
if grep -qi "PRIVATE_DNS_BROKEN" $OUT/pdns.txt; then echo "::error::PRIVATE_DNS_BROKEN flag on a network"; fail=1; fi

echo "----- core log -----"
adb shell run-as $PKG cat files/core.log > $OUT/core.log
tail -80 $OUT/core.log
# key lines as annotations (the job log itself is hard to read from outside)
ann() { local title="$1"; shift; local body; body=$("$@" 2>/dev/null | head -c 3500 | sed 's/%/%25/g' | sed ':a;N;$!ba;s/\n/%0A/g'); echo "::warning::$title%0A$body"; }
ann "core: errors/853/dns ($PDNS_MODE)" grep -iE "error|warn|:853|dns:|hijack|reject" $OUT/core.log
ann "core: last lines ($PDNS_MODE)" tail -25 $OUT/core.log
ann "connectivity: VPN/private DNS ($PDNS_MODE)" grep -iE "VPN|PrivateDns|DnsAddresses|Dns.*Validated" $OUT/connectivity.txt
ann "notification ($PDNS_MODE)" grep -iE -A4 "private.?dns" $OUT/notifications.txt

adb shell am start -n $PKG/.MainActivity --ez test_disconnect true
exit $fail
